### ISSUE TITLE
ERROR XPTY0004

### ISSUE THREAD

**Issue by arojascastro** [humboldtdigital/ProHD#10]
I am getting this error in the server installation, after searching some words and accessing the editions through the search page: 

```
the server did not return any content

La solicitud al servidor ha fallado.: exerr:ERROR XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: pages:get-content($config as map(*), $div as element()) item()*. Expected cardinality: exactly one, got 0. [at line 358, column 53, source: /db/apps/ProHD/modules/lib/api/document.xql] In function: pages:get-content(map(*), element()) [357:44:/db/apps/ProHD/modules/lib/pages.xql] dapi:get-fragment(map(*)) [176:30:/db/apps/ProHD/modules/lib/api/document.xql]. XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: pages:get-content($config as map(*), $div as element()) item()*. Expected cardinality: exactly one, got 0. [at line 358 of /db/apps/ProHD/modules/lib/api/document.xql]
```
not sure if it is the same as pointed in issue #5

**Comment by tuurma** [comment]
I can reproduce locally, e.g. query for "ports"

![image](https://user-images.githubusercontent.com/449468/135258780-5c0cabb2-7327-4220-b898-99ab791d4d31.png)

**Comment by tuurma** [comment]
Afaics it has something to do with erroneously retrieving the content in by page mode

**Comment by arojascastro** [comment]
Thank you! I updated the server installation with your changes. The problem is solved when searching a word, but now I have got an error message when accessing directly to the static websites. I think it is because in the statics pages div elements cannot be ingnore?

I am pasting the error message: 

`La solicitud al servidor ha fallado.: It is a type error if, during the static analysis phase, an expression is found to have a static type that is not appropriate for the context in which the expression occurs, or during the dynamic evaluation phase, the dynamic type of a value does not match a required type as specified by the matching rules in 2.5.4 SequenceType Matching. checking function parameter 1 in call util:node-id($doc): XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: util:node-id($node as node()) xs:string. Expected cardinality: exactly one, got 0. [at line 87 of /db/apps/ProHD/modules/map.xql] `

**Comment by tuurma** [comment]
@arojascastro can I please have a link to the problem or exact steps to make it manifest itself? It's very difficult to reproduce issues otherwise.

**Comment by tuurma** [comment]
Ok, I see the error e.g. http://localhost:8080/exist/apps/ProHD/about.xml

**Comment by arojascastro** [comment]
sorry, yes, I meant the about and team pages :)

**Comment by arojascastro** [comment]
Thanks a lot
