### ISSUE TITLE
Implementation eines "Share-Button"

### ISSUE THREAD

**Issue by windauer** [humboldtdigital/ProHD#26]

**Comment by windauer** [comment]
@arojascastro to deliver a sample and where it should be placed

**Comment by tuurma** [comment]
Effectively this Share-button should function also as a citation button with a content including:

- name of the online edition (@arojascastro please provide us with the exact text and format)
- title of the currently viewed document
- url of the current page
- current date

**Comment by arojascastro** [comment]
The content of the reference could be:

> "Title of the edition", Title of the publication as a whole, Publishers: URL with name of the file 

For this https://digitaldossier.ohc.cu/exist/apps/ProHD/prohd0021.xml it would be:

"Acta del Ayuntamiento de La Habana del 11 de enero de 1828 ", Dossier Digital: Alexander von Humboldt y Cuba (1800-1830), Berlin-Brandenburgische Akademie der Wissenschaften y Oficina del Historiador de la Ciudad de la Habana: https://digitaldossier.ohc.cu/exist/apps/ProHD/prohd0021.xml

I think the button could also be placed in the lateral panel after the new EPUB button.

**Comment by arojascastro** [comment]
One more remark: it is important to facilitate the copy and paste of the reference, so it would be cool to have an icon that says copy this reference or similar.

**Comment by arojascastro** [comment]
Sorry, @trafikante (Tobias) suggest that the editor of the edition should go after the title of the edition instead of the title of the publication... so it should be instead:

> "Title of the edition", name of the editor (ed.), Title of the publication as a whole, Publishers (current date): URL with name of the file

**Comment by tuurma** [comment]
Place it in the metadata drawer as well as on the browse page

**Comment by tuurma** [comment]
First draft:

<img width="1450" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/e2edaaf4-f130-4d6e-9f94-88f49107c77d">

**Comment by tuurma** [comment]
Alternative: in a popup

<img width="666" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/ec61335b-a584-4490-a54f-91b4f55a6f00">

**Comment by arojascastro** [comment]
Thanks. Pop up looks nicer. Specially if the user can copy it: is there a know function for that?

**Comment by tuurma** [comment]
`pb-clipboard` component was supposed to cover the "copy to clipboard" functionality but I discovered it doesn't work with complex content like we have here, just strings, so I'll need to extend the component or find another method

**Comment by arojascastro** [comment]
Hi! Thanks for your work!

We are reviewing the citation pop-up and have some questions:

- it would be better to add the full URL address (or is there any technical reason against it?)
- the citation pop-up is not very stable in IPad, Iphone and LG smatphones

Looking forwards to your comments. 

Thanks!

**Comment by tuurma** [comment]
Switched to collapsed section to avoid the popup, clicking on the copy icon copies to clipboard

<img width="447" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/9e4a9c76-8f06-454a-a52c-a12e3f8940db">
