### ISSUE TITLE
Unterstütze Sprachen Deutsch, Spanisch und Englisch

### ISSUE THREAD

**Issue by windauer** [humboldtdigital/ProHD#28]

**Comment by windauer** [comment]
@arojascastro will check what is required here, if this is a concrete or more a general issues.

**Comment by arojascastro** [comment]
I have checked the "Leistungsbeschreibung" and my initial notes, and this is not part of the requeriments, but a general remark. So basically what I meant is that please bear in mind those three languages, so for instance do not hardcore the labels into the interface but give them ids instead.

**Comment by arojascastro** [comment]
I think we can close this ticket.
