### ISSUE TITLE
Proxy and URL encoding

### ISSUE THREAD

**Issue by arojascastro** [humboldtdigital/ProHD#3]
When changing some parameters of the editions page, I get the following error message:

` Error message: the server did not return any contentDie Anfrage an den Server schlug fehl.: Document 1804-woodville-compendious.xml not found [at line 422 of /db/apps/ProHD/modules/lib/api/document.xql]`

See also attachment. 
![error_message](https://user-images.githubusercontent.com/7340111/131478055-51813f3d-309b-47ad-9c8d-1ce7d97c0120.PNG)

It seems is a server problem and @tuurma suggested to check this page: https://faq.teipublisher.com/general/proxy/

I asked Markus to do that change. At the moment, this is still pending. I will close this issue after confirmation by Markus and testing.

**Comment by tuurma** [comment]
Please, can we have a link to an actual document which demonstrates an error? As far as I can see, everything works right.

**Comment by arojascastro** [comment]
Yes, you are right. It is working perfectly. I am not sure if Markus fixed it or what, but we can close here. Thanks!
