### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by tuurma** [humboldtdigital/ProHD#34]
add a landing page following the mockup https://app.moqups.com/s9KP0THBCQUBvVAm9kOnrUOLOkpkfhhx/view/page/ad64222d5

<img width="1338" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/94f1e7d9-4a1c-4ea4-bf95-5fd20b482bb9">

**Comment by tuurma** [comment]
@arojascastro please, can we have the portrait image to use here?

**Comment by arojascastro** [comment]
I have also shared on Slack. 

![humboldt-edited](https://github.com/humboldtdigital/ProHD/assets/7340111/55def013-94ec-4705-aac1-aaaf8168f8b8)
![prohd_logo_400x400px](https://github.com/humboldtdigital/ProHD/assets/7340111/372d17ae-4956-4109-8df8-ef0e8778d4df)


Ps: I shared a zip with all the necessary images together with the guidelines via email some weeks ago

**Comment by tuurma** [comment]
wider displays

<img width="1308" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/e06636dd-c77f-4418-a34e-e01d10395064">

smaller

<img width="976" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/5e7f5db4-26ef-4e1d-8370-0ad2fccfbb1e">

smaller with the menu open

<img width="962" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/9342b41c-c6cd-426d-8107-1333ee8f7cbc">

@arojascastro if you could provide me with the 3 language versions of the text for the start page and the image caption, I could put it right in

**Comment by arojascastro** [comment]
Yes, I will try to send it to you today or tomorrow. Thanks

**Comment by arojascastro** [comment]
**EN**

Portrait of Alexander von Humboldt by Frédéric-Christophe d'Houdetot (1778-1859)

Proyecto Humboldt Digital (ProHD) is an international initiative for advanced training in the Digital Humanities at two locations: Havana (Casa Museo Alejandro de Humboldt) and Berlin (Berlin-Brandenburg Academy of Sciences and Humanities).

The project focuses on the study of Cuban scientific and literary culture of the 18th and 19th centuries, especially on the exploration of sources relevant to Alexander von Humboldt's research on Cuba during the period of 1800–1830.

This _Digital Dossier: Alexander von Humboldt and Cuba (1800–1830)_ contains transcriptions of textual documents in manuscript in three languages (English, French, and Spanish). They all relate to Humboldt's trip to Cuba and the questions the Prussian scientist studied in the _Essai politique sur l'île de Cuba_ (2 vols., Paris 1826).

**DE**

Porträt von Alexander von Humboldt von Frédéric-Christophe d'Houdetot (1778-1859).

Das Proyecto Humboldt Digital (ProHD) ist eine internationale Initiative zur Fortbildung in den Digital Humanities an zwei Standorten: Havanna (Casa Museo Alejandro de Humboldt) und Berlin (Berlin-Brandenburgische Akademie der Wissenschaften).

Das Projekt fokussiert sich auf das Erforschen der kubanischen wissenschaftlichen und literarischen Kultur des 18. und 19. Jahrhunderts, insbesondere auf die Erschließung von Quellen, die für Alexander von Humboldts Kuba-Forschung in der Zeit von 1800-1830 relevant sind.

Dieses _Digitale Dossier: Alexander von Humboldt und Kuba (1800-1830)_ enthält Transkriptionen von handschriftlichen Textdokumenten in drei Sprachen (Englisch, Französisch und Spanisch). Sie alle beziehen sich auf Humboldts Reise nach Kuba und die Fragen, die der preußische Wissenschaftler in dem _Essai politique sur l'île de Cuba_ (2 Bände, Paris 1826) untersucht hat..

**ES**

Retrato de Alexander von Humboldt por Frédéric-Christophe d'Houdetot (1778-1859).

El Proyecto Humboldt Digital (ProHD) es una iniciativa internacional para la formación avanzada en Humanidades Digitales en dos lugares: La Habana (Casa Museo Alejandro de Humboldt) y Berlín (Academia de Ciencias y Humanidades de Berlín-Brandeburgo).

El proyecto se centra en el estudio de la cultura científica y literaria cubana de los siglos XVIII y XIX, especialmente en la exploración de fuentes relevantes para la investigación de Alexander von Humboldt sobre Cuba durante el periodo de 
1800-1830.

Este _Dossier Digital: Alexander von Humboldt y Cuba (1800-1830)_ contiene transcripciones de documentos textuales manuscritos en tres idiomas (inglés, francés y español). Todos ellos se refieren al viaje de Humboldt a Cuba y a las cuestiones que el científico prusiano estudió en el _Essai politique sur l'île de Cuba_ (2 vols., París 1826).
