### ISSUE TITLE
facets with autocomplete

### ISSUE THREAD

**Issue by tuurma** [humboldtdigital/ProHD#41]
<img width="249" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/c3c143b0-d93e-4877-8b0b-81194a693106">

* author and subject get the search box with autocomplete 
* all others have limits exceeding the number of available options (language, institution, genre)
* all years are visible
* `show all` checkbox is removed

**Comment by humboldtdigital** [comment]
Perfect!
