### ISSUE TITLE
Localization of the interface

### ISSUE THREAD

**Issue by arojascastro** [humboldtdigital/ProHD#5]
We would like to enable access to the collection of texts in three languages: English, German and Spanish. 

At the moment, the default interface is partially localized into those languages, but some important parts are missing:

- [x]  Main menu 
- [x] and pages about the project and the team should be available in three languages
- [x] Browsing area, lateral sidebar (categories), should be in three languages
- [ ] Browsin area, drawer, the display of abstracts should be in German or Spanish
- [x] Footer in all pages should be also available in three languages
- [x] In each edition, the metadata section and menu bar should be available in three languages

Some screenshots here:

Browsing area

![browsing area](https://user-images.githubusercontent.com/7340111/131479503-004c1f9c-5ef7-477d-bb61-4a0116f39c3e.PNG)

Footer

![footer](https://user-images.githubusercontent.com/7340111/131479531-d7ae3bb9-4cdd-4d09-a65e-3dd824f6a7ae.PNG)

Pages

![about](https://user-images.githubusercontent.com/7340111/131479550-0555be7f-222d-4807-9c12-366f1726f12b.PNG)

Metadata and menu

![bar_metadata](https://user-images.githubusercontent.com/7340111/131479570-210b275d-bfb1-4f9b-9dfd-2d5a28c47b66.PNG)

**Comment by arojascastro** [comment]
I have tried to localize some parts of the interface:
- I have created three files in resources/i18n/app : https://github.com/humboldtdigital/ProHD/commit/a0570f76e73fd115f68cc2cea6ac749c8e07e4a7
- I have added a pb-i18n to localize "document.view-diplomatic": https://github.com/humboldtdigital/ProHD/commit/74112a2f600959d505dccaac47da213c665d7b5d

However, the results are not the expected ones. I will read again the documentation in the meating. Do you know what I am doingn wrong @tuurma ?

**Comment by arojascastro** [comment]
I have declared the path here `<pb-page data-template="pages:pb-page" unresolved="unresolved" locales="resources/i18n/{{ns}}/{{lng}}.json">` and now it seems it is working. I will keep localizing following this method. 

I keep this ticket open, because I am sure I will have new doubts or questions.

**Comment by arojascastro** [comment]
In committ afe1baa42192941818a4b9ed86a5f8453144130b I have internationalized with pb-i18n the text contained in HTML elements and in c22cb991902268726078648a941a314b5400e26f I have provided a translation into es, en, de.

To do:

- serve facets according to language
- serve abstract according to language
- serve page content according to language

I do not know how to do this... yet.

**Comment by tuurma** [comment]
Facets - see my recent commits

I've left the Subjects to port to translations for you, let me know if you need assistance

![image](https://user-images.githubusercontent.com/449468/132240108-883f96f0-bc0b-47c5-96a4-08ccbbb4948b.png)
![image](https://user-images.githubusercontent.com/449468/132240155-13f32f02-424f-4330-8aea-81ea19b875f5.png)

**Comment by tuurma** [comment]
Static pages (about) mostly done with c0236fba32ef65fe9d1d81c5a850bd2857e58180. TOC remains to be updated when changing the language

**Comment by arojascastro** [comment]
Thank you. 

I have updated the server installation with your last changes. I will have a look at your change and try to finish the subjects and the translation into Spanish in the following days.

**Comment by arojascastro** [comment]
Hello @tuurma I have translated the content of the static pages into three languages - you chan check the server installation or my latest commits here. 

However, I am failing to find out how to change the code in order to display the headings of each document on the left side. I have attached a screenshot.

![contents](https://user-images.githubusercontent.com/7340111/133589562-56de1f87-b9e8-42ab-8372-8b9bcc08a445.PNG)

I have looked at view-grid-prohd.html and the odd (the div element), but I cannot figure out. Can you help me here when possible? Thank you!

**Comment by arojascastro** [comment]
Also I have translated the subject labels and add the output to config.xqm (https://github.com/humboldtdigital/ProHD/commit/027fa63cc23daa047200b3f35ed9cffb1c3383cd) but the display of the subects is now missing -- see screenshot. 

![missing_subjects](https://user-images.githubusercontent.com/7340111/133597625-a439c413-145a-4abe-9cf4-3ea290ae6a0c.PNG)

**Comment by arojascastro** [comment]
The facet problem was solved thanks to @tuurma -- thanks a lot

**Comment by arojascastro** [comment]
Sadly, now, the display of the static pages in different languages is giving me an error sometimes:



```
the server did not return any content

La solicitud al servidor ha fallado.: It is a type error if, during the static analysis phase, an expression is found to have a static type that is not appropriate for the context in which the expression occurs, or during the dynamic evaluation phase, the dynamic type of a value does not match a required type as specified by the matching rules in 2.5.4 SequenceType Matching. checking function parameter 1 in call util:node-id($doc): XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: util:node-id($node as node()) xs:string. Expected cardinality: exactly one, got 0. [at line 87 of /db/apps/ProHD/modules/map.xql]
```

But If I  change the language, it works. Perhaps has something to do with 9c84faf5a30cebb0d15858b730329c75ae65868e  @tuurma ?

**Comment by arojascastro** [comment]
Closing here for now; we may work on the abstract in the future. Thank you @tuurma for your help !
