### ISSUE TITLE
pb-view cannot emit and subscribe to transcription at the same time?

### ISSUE THREAD

**Issue by arojascastro** [humboldtdigital/ProHD#7]
In prohd.html, I would like to allow the font to change and also display alternative views of the source with page view and diplomatic view. 

Originally, I had the following code:

`<pb-view id="view1" src="document1" xpath="//text" emit="transcription" wait-for="#facsimile"/>`

After adding `subscribe="transcription"` the font can be increased but the alternative presentation (diplomatic or page views) turn off and they are not working anymore. 

Aren't they incompatible? Can be this fixed somehow? 

Also, after turning off and on the diplomatic view I normally lose the title of the edition. 

See atacchments

Before 
![1](https://user-images.githubusercontent.com/7340111/131482750-b51aef2b-dca3-4a4b-9f91-e73ecdd81975.PNG)

After
![2](https://user-images.githubusercontent.com/7340111/131482780-c93b2006-8799-41e3-b79f-c3ae33aa0b49.PNG)

**Comment by tuurma** [comment]
fixed with 967df436b49130591d47c1363bff62294bff3ef8

**Comment by arojascastro** [comment]
Thank you. I uploaded the newer version to the server.
